services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./airflow/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 10

  airflow:
    image: apache/airflow:2.9.2-python3.11
    command: bash -c "pip install -r /opt/airflow/requirements.txt && airflow db upgrade && airflow users create --username airflow --firstname Air --lastname Flow --role Admin --email admin@example.com --password airflow || true && airflow webserver & airflow scheduler"
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/requirements.txt:/opt/airflow/requirements.txt
      - ./scripts:/opt/runners/scripts
      - ./rdm-api/statuses:/opt/catalog
      - ./confluence/templates:/opt/templates
    ports:
      - "8080:8080"
    depends_on:
      postgres:
         condition: service_healthy

  rdm-api:
    build:
      context: ./rdm-api
    env_file:
      - .env
    volumes:
      - ./rdm-api/statuses:/app/statuses
    ports:
      - "8000:8000"
